name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Check Formatting
        run: deno fmt --check --ignore=sqlite

      - name: Lint
        run: deno lint --ignore=sqlite

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Build sqlite3 (unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir -p build
          make
      
      - name: Setup MSVC Dev Env
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build sqlite3 (windows)
        if: matrix.os == 'windows-latest'
        run: deno task build-sqlite-win

      - name: Set DENO_SQLITE_PATH (linux)
        if: matrix.os == 'ubuntu-latest'
        run: echo "DENO_SQLITE_PATH=$(pwd)/build/libsqlite3.so" >> $GITHUB_ENV

      - name: Set DENO_SQLITE_PATH (macos)
        if: matrix.os == 'macos-latest'
        run: echo "DENO_SQLITE_PATH=$(pwd)/build/libsqlite3.dylib" >> $GITHUB_ENV

      - name: Set DENO_SQLITE_PATH (windows)
        if: matrix.os == 'windows-latest'
        run: echo "DENO_SQLITE_PATH=$(pwd)/build/sqlite3.dll" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run Tests
        run: deno task test

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release draft"
          draft: true
          files: |
            build/libsqlite3.so
            build/libsqlite3.dylib
            build/sqlite3.dll
